import os
import datetime
from core.display import (
    maGreen, maBold, display_validate, pointing, maMagenta, write_effect, display_info,
    maUnderline
)

date = datetime.datetime.now()
def save_data(file, title, text, pr, show):
    generated_spy_nexus = f'> 📂 File generated by SpyNexus\n> 🛠️ Creator and developer: [l-craft-l](https://github.com/l-craft-l)\n> 📅 Date this file was created: **{date}**\n\n---\n\n'

    if not os.path.exists(file):
        with open(file, pr) as file_data:
            file_data.write(generated_spy_nexus)

    with open(file, pr) as file_data:
        if title:
            file_data.write(title + '\n')
        if text:
            file_data.write(text + '\n')

    if show:
        write_effect(f"\n{display_validate} Saved successfully the info in: '{maBold(file)}' {maMagenta(pointing)}", 0.05)
        if file.endswith(".md"): write_effect(f"{display_info} This it seems a {maBold('Markdown file')}, you can see his content on this website:\n{display_info} {maBold('Stackedit.io')}: {maUnderline('https://stackedit.io/app#')}", 0.003)
